# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install poetry
      run: |
        python -m pip install poetry
    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: Lint with flake8
      run: |
        python -m poetry run python -m flake8
    - name: Test with pytest
      env:
        OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
        OPENAI_DEV_KEY: ${{secrets.OPENAI_DEV_KEY}}
      run: |
        python -m poetry run python -m pytest
    - name: Build package
      run: |
        python -m poetry build
    - name: Config poetry credential
      run: |
        python -m poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
    - name: Publish package
      run: |
        python -m poetry publish
