# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: develop
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install poetry
      run: |
        python -m pip install poetry
    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: Lint with flake8
      run: |
        python -m poetry run python -m flake8
    - name: Test with pytest
      env:
        OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
        OPENAI_DEV_KEY: ${{secrets.OPENAI_DEV_KEY}}
      run: |
        python -m poetry run python -m pytest
